developerportal: https://discord.com/developers/applications
discord.py_docs: https://discordpy.readthedocs.io/en/latest/index.html

hikari_apiwrapper: https://github.com/hikari-py/hikari
hikaridocs: https://www.hikari-py.dev/hikari/
